name: lando-dotnet-2
services:
  defaults:
    type: dotnet
    command: dotnet run
  cli:
    type: dotnet

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/dotnet": ./../../